# Generated by Django 3.0.6 on 2020-05-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBDRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(default=0)),
                ('speed_unit', models.CharField(max_length=20)),
                ('rpm', models.FloatField(default=0)),
                ('rpm_unit', models.CharField(max_length=20)),
                ('timestamp', models.IntegerField(default=0)),
                ('trip_id', models.IntegerField(default=0)),
            ],
        ),
    ]
