# Generated by Django 3.0.6 on 2020-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='obdrecord',
            name='rpm_unit',
        ),
        migrations.RemoveField(
            model_name='obdrecord',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='obdrecord',
            name='speed_unit',
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='ambiant_air_temp_celcius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='coolant_temp_celcius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='engine_load_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='engine_oil_temp_celcius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='fuel_level_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='fuel_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='intake_air_temp_celcius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='run_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='speed_kmph',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='obdrecord',
            name='throttle_percent',
            field=models.FloatField(default=0),
        ),
    ]
